# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0b8dd308fb8df8cb5b2689f498ad84af52b683ec71675c9d1ce029ea7feaf6f92b1f576cd485c0bdbc24ce76b5797d49b58cfb1b09752be8f5920f3816902d

test:
  secret_key_base: 8c910a76876c43234493274fe125482255aefd5142b13aae6de999ce1faec5c1daace39106b9cdeb2c330bf6f418b6d9fd18895332a260283dca0753643fbc8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
