# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88d53debfcd5124addfd82428f554a62e84e37c1c3dbea1168836b65d4cbd7b1a33e4032abcbb5d68d96520ff133a353ef4b6139a2bca5e755efbaf1eb5b632

test:
  secret_key_base: d518ac6078fad6a460b892b2ec8322184c4877b6a1c206ef98a76814f4ca529f92bfbdd1b86e20e583139e34f791a2a9149858d468547310374c0befb38ae0f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
